### PR TITLE
Fix text layouting for lines with no content

### LINKED ISSUE #3115: Including PyPlot and CairoMakie causes Segfaults, ReadOnlyMemoryErros and not drawn figures, depending on include order
# Including PyPlot before CairoMakie
When including the libraries in this order the more severe errors happen.

## Plotting with CairoMakie, but not showing the plot causes a segfault when saving

```
>>> ] activate --temp; add CairoMakie; add PyPlot
>>> using PyPlot
>>> using CairoMakie

>>> x = 0:0.1:10
>>> fig, ax, l = lines(x, sin.(x)); # <- do not show plot
>>> save("testfig.pdf", fig)

[30910] signal (11.1): Segmentation fault
```

<details><summary>Details, click to show</summary>
<p>

```
in expression starting at REPL[6]:1
cairo_surface_get_font_options at /workspace/srcdir/cairo-1.16.0/src/cairo-surface.c:1603
cairo_surface_get_font_options at /usr/lib/libcairo.so.2 (unknown line)
_pango_cairo_update_context at /workspace/srcdir/pango-1.50.9/build/../pango/pangocairo-context.c:111
pango_cairo_create_context at /workspace/srcdir/pango-1.50.9/build/../pango/pangocairo-context.c:453
pango_cairo_create_layout at /workspace/srcdir/pango-1.50.9/build/../pango/pangocairo-context.c:487
CairoContext at /home/nico/.julia/packages/Cairo/smWIA/src/Cairo.jl:558 [inlined]
Screen at /home/nico/.julia/packages/CairoMakie/Ry75I/src/screen.jl:281
Screen at /home/nico/.julia/packages/CairoMakie/Ry75I/src/screen.jl:266
unknown function (ip: 0x7f6fe23a1222)
unknown function (ip: 0x7f6ff2058420)
#getscreen#1103 at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:408
getscreen at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:391 [inlined]
#1099 at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:324
#open#409 at ./io.jl:395
open at ./io.jl:392 [inlined]
#save#1098 at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:319
save at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:297
unknown function (ip: 0x7f6fe239f10a)
#save#1097 at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:294
save at /home/nico/.julia/packages/Makie/uAmck/src/display.jl:291
unknown function (ip: 0x7f6fe239e07a)
unknown function (ip: 0x7f6ff206495c)
unknown function (ip: 0x7f6ff206413a)
unknown function (ip: 0x7f6ff206525b)
unknown function (ip: 0x7f6ff206613e)
unknown function (ip: 0x7f6ff2082502)
unknown function (ip: 0x7f6ff2082f19)
ijl_toplevel_eval_in at /usr/bin/../lib/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7f6fd8bb106c)
unknown function (ip: 0x7f6fd8bb20a5)
unknown function (ip: 0x7f6fd8bb2de6)
unknown function (ip: 0x7f6fd8bb43db)
unknown function (ip: 0x7f6fd8cb915b)
unknown function (ip: 0x7f6fd8cbed83)
unknown function (ip: 0x7f6fd8cbedbf)
unknown function (ip: 0x7f6fd8befe5a)
unknown function (ip: 0x7f6fd8befeab)
jl_f__call_latest at /usr/bin/../lib/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7f6fd9251582)
unknown function (ip: 0x7f6fd9259185)
unknown function (ip: 0x7f6fd925958f)
unknown function (ip: 0x7f6fd9259698)
unknown function (ip: 0x7f6ff20b0cf0)
jl_repl_entrypoint at /usr/bin/../lib/julia/libjulia-internal.so.1 (unknown line)
main at julia (unknown line)
unknown function (ip: 0x7f6ff2a4584f)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
_start at julia (unknown line)
Allocations: 31939197 (Pool: 31917041; Big: 22156); GC: 39
zsh: segmentation fault (core dumped)  julia


```

</p>
</details> 

## When trying to show the plot a ReadOnlyMemoryError is thrown
```
>>> ] activate --temp; add CairoMakie; add PyPlot
>>> using PyPlot
>>> using CairoMakie

>>> x = 0:0.1:10
>>> fig, ax, l = lines(x, sin.(x)) # <- do show plot
Error showing value of type Makie.FigureAxisPlot:
ERROR: ReadOnlyMemoryError()
```

<details><summary>Stacktrace, click to show</summary>
<p>

```
Stacktrace:
  [1] CairoContext
    @ ~/.julia/packages/Cairo/smWIA/src/Cairo.jl:558 [inlined]
  [2] CairoMakie.Screen(scene::Scene, config::CairoMakie.ScreenConfig, surface::Cairo.CairoSurfaceImage{ColorTypes.ARGB32})
    @ CairoMakie ~/.julia/packages/CairoMakie/Ry75I/src/screen.jl:281
  [3] Screen
    @ ~/.julia/packages/CairoMakie/Ry75I/src/screen.jl:266 [inlined]
  [4] CairoMakie.Screen(scene::Scene, config::CairoMakie.ScreenConfig)
    @ CairoMakie ~/.julia/packages/CairoMakie/Ry75I/src/screen.jl:252
  [5] getscreen(::Module, ::Scene; screen_config::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/uAmck/src/display.jl:408
  [6] getscreen
    @ ~/.julia/packages/Makie/uAmck/src/display.jl:391 [inlined]
  [7] display(figlike::Makie.FigureAxisPlot; backend::Module, inline::MakieCore.Automatic, update::Bool, screen_config::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/uAmck/src/display.jl:161
  [8] display(figlike::Makie.FigureAxisPlot)
    @ Makie ~/.julia/packages/Makie/uAmck/src/display.jl:131
  [9] (::REPL.var"#57#58"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL /usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:287
 [10] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:557
```

</p>
</details> 

# Including CairoMakie before PyPlot

When including the libraries in this order there are no segfaults and the correct pdfs are saved, however the matplotlib figure preview is not rendered.

```
>>> ] activate --temp; add CairoMakie; add PyPlot
>>> using CairoMakie
>>> using PyPlot

>>> x = 0:0.1:10
>>> fig, ax, l = lines(x, sin.(x)) # adding a ; here does not change the behavior
>>> save("testfig.pdf", fig)
>>> plt.plot(x, sin.(x)) # <- window opens, but no content is rendered
>>> plt.savefig("testfig-py.pdf")
```
# System and Environment information
I'm on julia version 1.9.2 with the following library versions:
 ```
>>> ] status
Status `/tmp/jl_0gTl5D/Project.toml`
  [13f3f980] CairoMakie v0.10.7
  [d330b81b] PyPlot v2.11.1
```
Running on Manjaro Linux:
```
>>> uname -a
Linux btptx1 6.1.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 x86_64 GNU/Linux
```
On dual Intel(R) Xeon(R) CPU E5-2640 v3, with a NVIDIA Quadro K2200.

### LINKED ISSUE #3315: Rich text errors on Strings with newlines
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?

```julia
julia> versioninfo()
Julia Version 1.9.1
Commit 147bdf428cd (2023-06-07 08:27 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, rocketlake)
  Threads: 16 on 16 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_IMAGE_THREADS = 1
```

MWE:
```julia
text(0,0, text=rich(rich("test", font = :bold), """

       more

       """))
```

Yields
```julia
ERROR: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
Stacktrace:
  [1] iterate
    @ ./tuple.jl:68 [inlined]
  [2] #map!#156
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:177 [inlined]
  [3] map!
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:171 [inlined]
  [4] #map#157
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:186 [inlined]
  [5] map
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:182 [inlined]
  [6] #initialize_block!#1466
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:311
--- the last 6 lines are repeated 1 more time ---
 [13] reduce_empty_iter
    @ ./reduce.jl:379 [inlined]
 [14] mapreduce_empty_iter(f::Function, op::Function, itr::Vector{Makie.GlyphInfo}, ItrEltype::Base.HasEltype)
    @ Base ./reduce.jl:375
 [15] Pairs
    @ ./essentials.jl:42 [inlined]
 [16] Pairs
    @ ./essentials.jl:46 [inlined]
 [17] pairs
    @ ./iterators.jl:275 [inlined]
 [18] LineAxis
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/lineaxis.jl:1 [inlined]
 [19] #initialize_block!#1466
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:323
 [20] #Figure#1234
    @ ~/.julia/packages/Makie/D4k7M/src/figures.jl:99
 [21] copyto!
    @ ./array.jl:319 [inlined]
 [22] append!
    @ ./array.jl:1122 [inlined]
 [23] #onany#155
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:167 [inlined]
 [24] onany
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:165 [inlined]
 [25] #initialize_block!#1466
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:509
 [26] getproperty
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:59 [inlined]
 [27] getindex
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:97 [inlined]
 [28] to_value
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:105 [inlined]
 [29] map (repeats 3 times)
    @ ./tuple.jl:276 [inlined]
 [30] #map#157
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:185 [inlined]
 [31] map
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:182 [inlined]
 [32] #initialize_block!#1466
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:466
 [33] getproperty
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:59 [inlined]
 [34] getindex
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:97 [inlined]
 [35] to_value
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:105 [inlined]
 [36] map (repeats 13 times)
    @ ./tuple.jl:276 [inlined]
 [37] MapCallback
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:431 [inlined]
 [38] #map!#156
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:178 [inlined]
 [39] map!
    @ ~/.julia/packages/Makie/D4k7M/src/scenes.jl:171 [inlined]
 [40] #initialize_block!#1466
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:482
 [41] log10
    @ ./special/log.jl:265 [inlined]
 [42] apply_transform
    @ ~/.julia/packages/Makie/D4k7M/src/layouting/transformation.jl:304 [inlined]
 [43] apply_transform
    @ ~/.julia/packages/Makie/D4k7M/src/layouting/transformation.jl:346 [inlined]
 [44] update_axis_camera
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:80
 [45] ComposedFunction
    @ ./operators.jl:1031 [inlined]
 [46] (::Makie.var"#2141#2144"{Base.RefValue{Vector{Int64}}, Observable{Vector{ColorTypes.RGBA{Float32}}}, Observable{Vector{Float32}}, Observable{Vector{Point{2, Float32}}}, Observable{Vector{Makie.GlyphCollection}}})(str::Makie.RichText, ts::Int64, f::Symbol, fs::Attributes, al::Tuple{Symbol, Symbol}, rot::Float64, jus::MakieCore.Automatic, lh::Float64, col::ColorTypes.RGBA{Float32}, scol::Tuple{Symbol, Float64}, swi::Int64, www::Int64, offs::Tuple{Float64, Float64})
    @ Makie ~/.julia/dev/Makie/src/basic_recipes/text.jl:45
 [47] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
 [48] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
 [49] (::Observables.OnAny)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:415
 [50] getindex
    @ ./essentials.jl:13 [inlined]
 [51] iterate (repeats 2 times)
    @ ./array.jl:893 [inlined]
 [52] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:168 [inlined]
 [53] setindex!
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86 [inlined]
 [54] #1355
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/mousestatemachine.jl:218
 [55] macro expansion
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/mousestatemachine.jl:183 [inlined]
 [56] macro expansion
    @ ~/.julia/packages/Match/XemzX/src/matchmacro.jl:410 [inlined]
 [57] #1355
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/mousestatemachine.jl:182
 [58] plot!(plot::MakieCore.Text{Tuple{Vector{Point{2, Float32}}}})
    @ Makie ~/.julia/dev/Makie/src/basic_recipes/text.jl:66
 [59] plot!(scene::Scene, P::Type{MakieCore.Text{Tuple{Int64, Int64}}}, attributes::Attributes, input::Tuple{Observable{Int64}, Observable{Int64}}, args::Observable{Tuple{Vector{Point{2, Float32}}}})
    @ Makie ~/.julia/dev/Makie/src/interfaces.jl:398
 [60] plot!(::Scene, ::Type{MakieCore.Text}, ::Attributes, ::Int64, ::Vararg{Int64}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/dev/Makie/src/interfaces.jl:310
 [61] plot!(::Scene, ::Type{MakieCore.Text}, ::Attributes, ::Int64, ::Int64)
    @ Makie ~/.julia/dev/Makie/src/interfaces.jl:275
 [62] #initialize_block!#1466
    @ ~/.julia/packages/Makie/D4k7M/src/makielayout/blocks/axis.jl:233
 [63] plot(::Type{MakieCore.Text}, ::Int64, ::Vararg{Int64}; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Pairs{Symbol, Makie.RichText, Tuple{Symbol}, NamedTuple{(:text,), Tuple{Makie.RichText}}})
    @ Makie ~/.julia/dev/Makie/src/figureplotting.jl:65
 [64] text(::Int64, ::Vararg{Int64}; attributes::Base.Pairs{Symbol, Makie.RichText, Tuple{Symbol}, NamedTuple{(:text,), Tuple{Makie.RichText}}})
    @ MakieCore ~/.julia/packages/MakieCore/7iPhv/src/recipes.jl:35
```

Additionally
```julia
text(rich("test"))
```
Throws a different error.

### PR DESCRIPTION
**Pull request by asinghvi17**
# Description

Fixes #3315

This PR adds an `init` kwarg to the reducers in the `max_y_ascender` and `min_y_descender` functions.  Local tests work but I'm not sure if this change breaks text layouting elswhere because of the `init` values chosen.

## Type of change

Delete options that do not apply:

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [X] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: src/basic_recipes/text.jl [hunk 1]
```diff
@@ -415,13 +415,13 @@ function max_x_advance(glyph_infos::Vector{GlyphInfo})::Float32
 end
 
 function max_y_ascender(glyph_infos::Vector{GlyphInfo})::Float32
-    return maximum(glyph_infos) do ginfo
+    maximum(glyph_infos; init = 0.0f0) do ginfo
```
Comment (SimonDanisch) [inline src/basic_recipes/text.jl:418]: Why not -Inf?

Comment (asinghvi17) [reply src/basic_recipes/text.jl:418]: Then you have to insert a check prior to returning (though I guess that's more accurate)

**Comment by ffreyer** [comment]
Does this also happen to fix #3791 and #3315?

**Comment by asinghvi17** [comment]
#3791 has a different error now:

```julia

ERROR: TypeError: in new, expected Makie.ScalarOrVector{Quaternionf}, got a value of type Makie.ScalarOrVector{Any}
Stacktrace:
  [1] Makie.GlyphCollection(glyphs::Vector{…}, fonts::Vector{…}, origins::Vector{…}, extents::Vector{…}, scales::Vector{…}, rotations::Vector{…}, colors::Vector{…}, strokecolors::Vector{…}, strokewidths::Vector{…})
    @ Makie ~/.julia/dev/Makie/src/types.jl:451
  [2] Makie.GlyphCollection(v::Vector{Makie.GlyphInfo})
    @ Makie ~/.julia/dev/Makie/src/basic_recipes/text.jl:363
  [3] layout_text(rt::Makie.RichText, ts::Float32, f::FreeTypeAbstraction.FTFont, fset::Attributes, al::Tuple{Symbol, Symbol}, rot::Quaternionf, jus::Symbol, lh::Float32, col::ColorTypes.RGBA{Float32})
    @ Makie ~/.julia/dev/Makie/src/basic_recipes/text.jl:390
  [4] _get_glyphcollection_and_linesegments(rt::Makie.RichText, index::Int64, ts::Float32, f::FreeTypeAbstraction.FTFont, fset::Attributes, al::Tuple{…}, rot::Quaternionf, jus::Symbol, lh::Float32, col::ColorTypes.RGBA{…}, scol::ColorTypes.RGBA{…}, swi::Int64, www::Float32, offs::Vec{…})
    @ Makie ~/.julia/dev/Makie/src/basic_recipes/text.jl:314
```

#3315 was the original issue, I had a typo in the PR description :D

File: src/basic_recipes/text.jl (hunk 1 above)
Comment (SimonDanisch) [reply src/basic_recipes/text.jl:418]: Why? Inf as return value for an empty list seems as valid as 0, no?

Comment (ffreyer) [reply src/basic_recipes/text.jl]: Inf also produces NaN down the line. Not sure if that's a problem so I'm trying +-floatmax(Float32) instead.

I think ascenders and descenders can be pretty wild so using 0 is probably wrong in some cases?
