### PR TITLE
Split marker_offset from quad_offset

### LINKED ISSUE #4383: Scatter `marker_offset` is broken
I get this in CairoMakie and GLMakie with Makie v0.21.11, the dots should be separated.

```julia
scatter([1, 1, 1], [1, 1, 1], marker_offset = [(10, 10), (0, 20), (-15, -15)])
```

image

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

For `text` we have:
- a position that acts as an anchor for the displayed string
- a `char_offset` which gives the position of each character relative to the string anchor point
- a `quad_offset` which gives places the rectangle containing the char relative to the character position

The user `offset` is included in `char_offset`. Both act in markerspace, though `quad_offset` also includes billboarding.

This pr effective translates this behavior to scatter. It now always centers, i.e. does the equivalent to character layouting under the hood, and considers `marker_offset` a pure user attribute. This removes the need for
https://github.com/MakieOrg/Makie.jl/blob/66c32da63145c2875fda522a422fce7b156c292e/src/interfaces.jl#L66-L71
in calculated_attributes, and it also fixes some niche errors:
- Bezierpath markers ignoring marker_offset (GLMakie, WGLMakie, CairoMakie)
- Char markers being complicated to center (GLMakie, WGLMakie) (using 0.5markersize doesn't quite work here)
- FastPixel ignoring marker_offset (GLMakie)
- marker_offset not working without billboarding in 3D (GLMakie, WGLMakie)
- Image markers translating in the wrong direction (CairoMakie)
- rotation acting on the position rather than marker for Rect (and FastPixel) markers (CairoMakie)

Changes:
- marker_offset is now independent of `rotation`. (So `rotation = pi/2` doesn't turn `(x, 0)` into a translation in y direction) (GLMakie, WGLMakie)

Fixes #4383

### 2D no rotation

FastPixel is expected to be square in GLMakie, falls back onto Rect for other backends

| | GLMakie | WGLMakie | CairoMakie |
| --- | --- | --- | --- |
| before | Screenshot 2024-11-17 173436 | Screenshot 2024-11-17 173837 | Screenshot 2024-11-17 174035 |
| after | GLMakie_scatter marker_offset 2D | WGLMakie_scatter marker_offset 2D | CairoMakie_scatter marker_offset 2D |

### 2D with billboarded rotation

Skipped FastPixel as it doesn't support rotation

| | GLMakie | WGLMakie | CairoMakie |
| --- | --- | --- | --- |
| before | Screenshot 2024-11-17 173516 | Screenshot 2024-11-17 173900 | Screenshot 2024-11-17 174047 |
| after | GLMakie_scatter marker_offset 2D with billboarded rotation | WGLMakie_scatter marker_offset 2D with billboarded rotation | CairoMakie_scatter marker_offset 2D with billboarded rotation |

### 3D with Quaternion rotation

Everything is wrong in CairoMakie here, especially with `space = :data`. I assume fixing this requires reworking the scatter code at a larger scale, so I didn't bother with it here. Some placements improved regardless though.

| | GLMakie | WGLMakie | CairoMakie |
| --- | --- | --- | --- |
| before | Screenshot 2024-11-17 173609 | Screenshot 2024-11-17 173916 | image |
| after | GLMakie_scatter marker_offset 3D with rotation | WGLMakie_scatter marker_offset 3D with rotation | Screenshot 2024-11-17 153837 |

## Attribute Example

image

## Type of change

Could be considered breaking as `marker_offset = Vec2f(0, 0)` is now a centered marker instead of a bottom-left aligned marker. But with BezierPath, i.e. default markers not working with marker_offset we could also consider marker_offset to not really be supported right now.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [x] Updated docstring
- [x] Added or changed relevant sections in the documentation
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
I'd consider this a bug fix

**Comment by ffreyer** [comment]
This is ready for review

File: WGLMakie/src/particles.jl [hunk 1]
```diff
@@ -170,7 +170,8 @@ function scatter_shader(scene::Scene, attributes, plot)
 
         markersize = lift(Makie.to_2d_scale, plot, attributes[:markersize])
 
-        msize, offset = Makie.marker_attributes(atlas, marker, markersize, font, attributes[:quad_offset], plot)
+        # TODO: Is this going to be very wrong with text?
+        msize, offset = Makie.marker_attributes(atlas, marker, markersize, font, plot)
```
Comment (SimonDanisch) [inline WGLMakie/src/particles.jl:174]: What does this TODO mean? Isn't this heavily tested with test?

**Review by SimonDanisch — APPROVED** [review]
