### PR TITLE
Fix CairoMakie not being able to plot exotic point arrays in lines

### LINKED ISSUE #4661: CairoMakie: `lines` fails if `transform_func` is not identity, and the input is not a pure Vector
- [ ] what version of Makie are you running? (`]st -m Makie`) 0.21.17
- [ ] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) yes
- [x] What platform + GPU are you on? irrelevant

`lines` and `linesegments` fail to render when the input is an `AbstractVector{Point}` but not a `Vector{Point}`, looks like this was caused by the type annotation on `apply_transform` in #4601.  If the input is something like a ReinterpretArray, or any abstract vector of points, then this fails.

MWE:
```julia
using CairoMakie
data = reinterpret(Point2f, rand(Point2f, 4) .=> rand(Point2f, 4))
lines(data; axis = (; xscale = log10))
```

Error:
```julia
Error showing value of type Makie.FigureAxisPlot:
ERROR: TypeError: in typeassert, expected Base.ReinterpretArray{Point{2, Float32}, 1, Pair{Point{2, Float32}, Point{2, Float32}}, Vector{Pair{Point{2, Float32}, Point{2, Float32}}}, false}, got a value of type Vector{Point{2, Float32}}
Stacktrace:
  [1] project_line_points(scene::Scene, plot::LineSegments{…}, positions::Base.ReinterpretArray{…}, colors::ColorTypes.RGBA{…}, linewidths::Float32)
    @ CairoMakie ~/.julia/dev/Makie/CairoMakie/src/utils.jl:204
  [2] draw_atomic(scene::Scene, screen::CairoMakie.Screen{CairoMakie.IMAGE}, primitive::Union{Lines, LineSegments})
    @ CairoMakie ~/.julia/dev/Makie/CairoMakie/src/primitives.jl:36
  [3] draw_plot(scene::Scene, screen::CairoMakie.Screen{CairoMakie.IMAGE}, primitive::LineSegments{Tuple{Base.ReinterpretArray{…}}})
    @ CairoMakie ~/.julia/dev/Makie/CairoMakie/src/infrastructure.jl:135
  [4] cairo_draw(screen::CairoMakie.Screen{CairoMakie.IMAGE}, scene::Scene)
    @ CairoMakie ~/.julia/dev/Makie/CairoMakie/src/infrastructure.jl:49
  [5] display(screen::CairoMakie.Screen{CairoMakie.IMAGE}, scene::Scene; connect::Bool, screen_config::@Kwargs{})
    @ CairoMakie ~/.julia/dev/Makie/CairoMakie/src/display.jl:45
  [6] display(screen::CairoMakie.Screen{CairoMakie.IMAGE}, scene::Scene)
    @ CairoMakie ~/.julia/dev/Makie/CairoMakie/src/display.jl:40
  [7] display(figlike::Makie.FigureAxisPlot; backend::Module, inline::MakieCore.Automatic, update::Bool, screen_config::@Kwargs{})
    @ Makie ~/.julia/dev/Makie/src/display.jl:166
```

It's fine if the transform_func is identity, presumably because that's a no-op.

I see one solution here, wrap all of the function `project_line_points` beyond this line in a function barrier:

https://github.com/MakieOrg/Makie.jl/blob/88eb6fe1164a790caba76594be2ac0ad74971957/CairoMakie/src/utils.jl#L204

We could somehow extract the point type from `positions`, but this would then cause failures when `transform_func = identity`.

### PR DESCRIPTION
**Pull request by asinghvi17**
# Description

Fixes #4661

Splits out the CairoMakie `project_line_points` into a main entry point that applies `transform_func`, and a second internal function.

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [x] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: CairoMakie/src/utils.jl [hunk 1]
```diff
@@ -193,16 +193,25 @@ end
 
 
 
-function project_line_points(scene, plot::T, positions, colors, linewidths) where {T <: Union{Lines, LineSegments}}
+function project_line_points(scene, plot::T, positions::AbstractArray{<: Makie.VecTypes{N, FT}}, colors, linewidths) where {T <: Union{Lines, LineSegments}, N, FT <: Real}
+
+    # Standard transform from input space to clip space
+    # Note that this is type unstable, so there is a function barrier in place.
+    space = (plot.space[])::Symbol
+    points = Makie.apply_transform(transform_func(plot), positions, space)::AbstractVector{Point{N, FT}}
```
Comment (asinghvi17) [inline CairoMakie/src/utils.jl:201]:
```suggestion
    points = Makie.apply_transform(transform_func(plot), positions, space)
```

**Review by ffreyer — APPROVED** [review]

**Comment by SimonDanisch** [comment]
Thanks!
