### PR TITLE
GLMakie: ignore mouse buttons beyond the first three

### LINKED ISSUE #3125: Mice with more than three buttons cause errors
I've got a five-button mouse and accidentally pressed one of the additional buttons while hovering over a GLMakie Figure (Ubuntu 22.04, Julia 1.9.2, GLMakie 0.8.7). This triggered an error in the renderloop because mouse buttons are represented via an Enum (`Mouse.Button`) limited to three values (see error message below). 

While this is not fatal or serious (at least for me, given that I never use the additional mouse buttons on purpose), it would be nice to fix this or at least supress the error message.
Given that the mouse button Enum in `GLFW` supports up to 8 buttons, maybe this would be appropriate here as well?

```
Error in callback:
ArgumentError: invalid value for Enum Button: 4
Stacktrace:
 [1] enum_argument_error(typename::Symbol, x::Int64)
   @ Base.Enums ./Enums.jl:93
 [2] Button
   @ ./Enums.jl:211 [inlined]
 [3] (::GLMakie.var"#mousebuttons#153"{Observable{Makie.MouseButtonEvent}})(window::GLFW.Window, button::GLFW.MouseButton, action::GLFW.Action, mods::Int32)
   @ GLMakie /data.lmp/$USER/.julia/packages/GLMakie/9nid7/src/events.jl:102
 [4] _MouseButtonCallbackWrapper(window::GLFW.Window, button::GLFW.MouseButton, action::GLFW.Action, mods::Int32)
   @ GLFW /data.lmp/$USER/.julia/packages/GLFW/BWxfF/src/callback.jl:43
 [5] PollEvents
   @ /data.lmp/$USER/.julia/packages/GLFW/BWxfF/src/glfw3.jl:620 [inlined]
 [6] pollevents(screen::GLMakie.Screen{GLFW.Window})
   @ GLMakie /data.lmp/$USER/.julia/packages/GLMakie/9nid7/src/screen.jl:421
 [7] on_demand_renderloop(screen::GLMakie.Screen{GLFW.Window})
   @ GLMakie /data.lmp/$USER/.julia/packages/GLMakie/9nid7/src/screen.jl:876
 [8] renderloop(screen::GLMakie.Screen{GLFW.Window})
   @ GLMakie /data.lmp/$USER/.julia/packages/GLMakie/9nid7/src/screen.jl:902
 [9] (::GLMakie.var"#69#70"{GLMakie.Screen{GLFW.Window}})()
   @ GLMakie ./task.jl:514
```

### PR DESCRIPTION
**Pull request by jwahlstrand**
# Description

Fixes #3125

Prevents an error from being thrown when you press an exotic mouse button. Allowing those buttons to be used would require additions to mousestatemachine.

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thanks :)

File: GLMakie/src/events.jl [hunk 1]
```diff
@@ -99,7 +99,9 @@ function Makie.mouse_buttons(scene::Scene, window::GLFW.Window)
     event = scene.events.mousebutton
     function mousebuttons(window, button, action, mods)
         @print_error begin
-            event[] = MouseButtonEvent(Mouse.Button(Int(button)), Mouse.Action(Int(action)))
+            if Int(button) < 3  # ignore mouse buttons beyond 3
```
Comment (SimonDanisch) [inline GLMakie/src/events.jl:102]: Should we ignore them, or just pass through?

Comment (jwahlstrand) [reply GLMakie/src/events.jl:102]: I got an error in makielayout/mousestatemachine.jl.

To allow extra buttons to be used, the enum `MouseEventTypes` would need to be expanded hugely, and all the `@match` uses in that file too. I'd be willing to go through and do that if it's of interest.

Comment (SimonDanisch) [reply GLMakie/src/events.jl:102]: Ok, I think we should merge this PR first then, and fix this once demand arises!

Comment (jwahlstrand) [reply GLMakie/src/events.jl:102]: Sounds good. I have a mouse with lots of buttons on the side and I'm almost always annoyed when they actually do something!

Comment (ffreyer) [reply GLMakie/src/events.jl:102]: I think rather than discarding the event we should ignore it in mousestatemachine then.
