### PR TITLE
Handle heatmap, image, meshscatter, mesh and surface in Legend

### LINKED ISSUE #1703: `Legend` fails on a 3D plot ?
On a basic example, it seems `Legend` does not work on 3D axes, is it normal ?

```julia
f,ax,p = meshscatter(rand(10),rand(10),rand(10))
Legend(f[1,2],p,"test")
```

### LINKED ISSUE #4066: meshscatter does not produce an element in the legend
I noted that `meshscatter` does not produce a symbol in the legend and trying to create a MWE I got the following:

```julia-repl
julia> fig = Figure()

julia> ax = Axis3(fig[1, 1])
Axis3()

julia> meshscatter!(ax, 1, 1, 1, label = "hello")
MeshScatter{Tuple{Vector{Point{3, Float64}}}}

julia> Legend(fig[1, 2], ax)
ERROR: `legendelements` returned an empty list for content element of type MeshScatter{Tuple{Vector{Point{3, Float64}}}}. That could mean that neither this object nor any possible child objects had a method for `legendelements` defined that returned a non-empty result.
Stacktrace:
```

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

More or less inspired by #2348, this adds Legend elements for image, heatmap, meshscatter, mesh and surface.

Refimg/Example:
image

Fixes #1703
Fixes #4066

When this or #2276 is merged, the other will need to add plots to LegendElements.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by asinghvi17** [comment]
Awesome, thanks for taking that forward!

File: src/makielayout/blocks/legend.jl [hunk 1]
```diff
@@ -450,6 +519,9 @@ _renaming_mapping(::Type{PolyElement}) = Dict(
     :colormap => :polycolormap,
     :colorrange => :polycolorrange,
 )
+_renaming_mapping(::Type{MeshElement}) = Dict()
+_renaming_mapping(::Type{ImageElement}) = Dict()
+_renaming_mapping(::Type{MeshScatterElement}) = Dict()
```
Comment (ffreyer) [inline src/makielayout/blocks/legend.jl:524]: What's the point of these? They just seem to map the simpler attribute names in a LegendElement to more complicated ones like `color -> polycolor`. But the attributes are already isolated there. Am I missing something?

**Review by SimonDanisch — APPROVED** [review]

File: src/makielayout/blocks/legend.jl (hunk 1 above)
Comment (ffreyer) [reply src/makielayout/blocks/legend.jl:541]: @jkrumbiegel Is it fine to leave these?
