### PR TITLE
fix updates for multiple meshes

### LINKED ISSUE #2200: Metadata length mismatch when using contourf! on an observable.
I'm getting familiarized with Makie and wanting to make quick UI for observing the optimization error maps. Right now I'm plotting random data and may have encountered a bug when using contourf! on random data. MWE and error below:

System: Windows 10 / AMD Ryzen 7 2700U / 8GB ram / AMD Radeon RX Vega 10
Version: GLMakie / Makie v0.17.13

```Julia
using GLMakie
GLMakie.activate!()

# stuff which will eventually be found by the error plot
n = 10
testdata = rand(n, n, n)


START_SLICE = 4


fig = Figure()
sl_ρ = Slider(fig[1, 2], range = 1:n, startvalue = START_SLICE, horizontal=false)

# empty!(f)
grid_views = GridLayout()
fig.layout[1, 1] = grid_views

# limits!(ax, 0, 10, 0, 10)
main_view_axis = Axis3(fig, aspect=:data, )
constant_pstar_axis = Axis(fig)
constant_tstar_axis = Axis(fig)
constant_ρstar_axis = Axis(fig)
grid_views[1, 1] = main_view_axis
grid_views[1, 2] = constant_pstar_axis
grid_views[2, 1] = constant_ρstar_axis
grid_views[2, 2] = constant_tstar_axis
main_view_plot = contour!(main_view_axis, testdata)

# interactivity
get_slice_data(slice_val) = @view testdata[:, :, slice_val]
slice = lift(get_slice_data, sl_ρ.value)
constant_pstar_plot = contourf!(constant_pstar_axis, slice)

function create_rectangle_indicator_positions(height)
    return [
        (-1, -1, height), (n+1, -1, height),
        (n+1, -1, height), (n+1, n+1, height), 
        (n+1, n+1, height), (-1, n+1, height), 
        (-1, n+1, height), (-1, -1, height)
    ]
end
rectangle_indicator_positions = lift(create_rectangle_indicator_positions, sl_ρ.value)
# rectangle_indicator_positions = Observable(create_rectangle_indicator_positions(START_SLICE))
linesegments!(main_view_axis, rectangle_indicator_positions, linewidth=3, color=:red)


fig
```

Upon moving the slider, the following (quite long) stacktrace occurs for me

```        
julia> Error in callback:
Metadata array needs to have same length as data.
                    Found 1434 data items, and 1324 metadata items
Stacktrace:
   [1] error(s::String)
     @ Base .\error.jl:33
   [2] #meta#122
     @ C:\Users\Will Laptop\.julia\packages\GeometryBasics\5Sb5M\src\metadata.jl:125 [inlined]
   [3] pointmeta(mesh::GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}; meta_data::Base.Pairs{Symbol, Vector{Float32}, Tuple{Symbol}, NamedTuple{(:color,), Tuple{Vector{Float32}}}})
     @ GeometryBasics C:\Users\Will Laptop\.julia\packages\GeometryBasics\5Sb5M\src\meshes.jl:253
   [4] (::GLMakie.var"#238#241")(mesh::GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}, color::Vector{Float32})
     @ GLMakie C:\Users\Will Laptop\.julia\packages\GLMakie\K6iJk\src\drawing_primitives.jl:466
   [5] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
   [6] invokelatest
     @ .\essentials.jl:714 [inlined]
   [7] #15
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:393 [inlined]
   [8] (::Observables.var"#callback#13"{Observables.var"#15#16"{GLMakie.var"#238#241", Observable{GeometryBasics.Mesh{2, Float32, GeometryBasics.TriangleP{2, Float32, GeometryBasics.PointMeta{2, Float32, Point{2, Float32}, (:color,), Tuple{Float32}}}, GeometryBasics.FaceView{GeometryBasics.TriangleP{2, Float32, GeometryBasics.PointMeta{2, Float32, Point{2, Float32}, (:color,), Tuple{Float32}}}, GeometryBasics.PointMeta{2, Float32, Point{2, Float32}, (:color,), Tuple{Float32}}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}, StructArrays.StructVector{GeometryBasics.PointMeta{2, Float32, Point{2, Float32}, (:color,), Tuple{Float32}}, NamedTuple{(:position, :color), Tuple{Vector{Point{2, Float32}}, Vector{Float32}}}, Int64}, Vector{GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, Tuple{Observable{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}, Observable{Vector{Float32}}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
   [9] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [10] invokelatest
     @ .\essentials.jl:714 [inlined]
  [11] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [12] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
--- the last 6 lines are repeated 1 more time ---
  [19] (::Observables.var"#8#9"{Observable{Any}})(x::Vector{Float32})
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:120
  [20] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [21] invokelatest
     @ .\essentials.jl:714 [inlined]
  [22] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [23] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
--- the last 5 lines are repeated 1 more time ---
  [29] (::Observables.var"#6#7"{Observable{Any}})(x::Vector{Float32})
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:114
  [30] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [31] invokelatest
     @ .\essentials.jl:714 [inlined]
  [32] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [33] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
  [34] #15
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:393 [inlined]
  [35] (::Observables.var"#callback#13"{Observables.var"#15#16"{Makie.var"#558#561"{Attributes}, Observable{Union{ColorTypes.RGBA{Float32}, Vector{ColorTypes.RGBA{Float32}}, Vector{Float32}, Makie.AbstractPattern, Matrix{ColorTypes.RGBA{Float32}}}}}, Tuple{Observable{Any}, Observable{Vector{Int64}}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
--- the last 6 lines are repeated 2 more times ---
  [48] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [49] invokelatest
     @ .\essentials.jl:714 [inlined]
  [50] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [51] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
  [52] (::Makie.var"#142#144"{Attributes, Observable{Tuple{Vector{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, DataType})(kwargs::Tuple{}, args::Tuple{Vector{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}})
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\interfaces.jl:333
  [53] (::Observables.var"#callback#13"{Makie.var"#142#144"{Attributes, Observable{Tuple{Vector{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}, DataType}, Tuple{Observable{Tuple{}}, Observable{Tuple{Vector{GeometryBasics.Mesh{2, Float32, GeometryBasics.Ngon{2, Float32, 3, Point{2, Float32}}, GeometryBasics.SimpleFaceView{2, Float32, 3, GeometryBasics.OffsetInteger{-1, UInt32}, Point{2, Float32}, GeometryBasics.NgonFace{3, GeometryBasics.OffsetInteger{-1, UInt32}}}}}}}}})(x::Any) 
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
--- the last 24 lines are repeated 1 more time ---
  [78] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [79] invokelatest
     @ .\essentials.jl:714 [inlined]
  [80] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [81] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
  [82] #15
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:393 [inlined]
  [83] (::Observables.var"#callback#13"{Observables.var"#15#16"{typeof(tuple), Observable{Tuple{Vector{GeometryBasics.Polygon{2, Float32, Point{2, Float32}, GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}, Vector{GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}}}}}}}, Tuple{Observable{Vector{GeometryBasics.Polygon{2, Float32, Point{2, Float32}, GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}, Vector{GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}}}}}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
  [84] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [85] invokelatest
     @ .\essentials.jl:714 [inlined]
  [86] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [87] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
  [88] (::Makie.var"#calculate_polys#451"{Observable{Vector{Float64}}, Observable{Vector{GeometryBasics.Polygon{2, Float32, Point{2, Float32}, GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}, Vector{GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}}}}}})(xs::StepRangeLen{Float32, Float64, Float64, Int64}, ys::StepRangeLen{Float32, Float64, Float64, Int64}, zs::Matrix{Float32}, levels::Vector{Float32}, is_extended_low::Bool, is_extended_high::Bool)
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\basic_recipes\contourf.jl:167
  [89] (::Observables.var"#callback#13"{Makie.var"#calculate_polys#451"{Observable{Vector{Float64}}, Observable{Vector{GeometryBasics.Polygon{2, Float32, Point{2, Float32}, GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}, Vector{GeometryBasics.LineString{2, Float32, Point{2, Float32}, Base.ReinterpretArray{GeometryBasics.Line{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, GeometryBasics.TupleView{Tuple{Point{2, Float32}, Point{2, Float32}}, 2, 1, Vector{Point{2, Float32}}}, false}}}}}}}, Tuple{Observable{StepRangeLen{Float32, Float64, Float64, Int64}}, Observable{StepRangeLen{Float32, Float64, Float64, Int64}}, Observable{Matrix{Float32}}, Observable{Any}, Observable{Bool}, Observable{Bool}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
  [90] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [91] invokelatest
     @ .\essentials.jl:714 [inlined]
  [92] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [93] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
  [94] (::Observables.var"#6#7"{Observable{Any}})(x::Vector{Float32})
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:114
  [95] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
  [96] invokelatest
     @ .\essentials.jl:714 [inlined]
  [97] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
  [98] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
  [99] #15
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:393 [inlined]
 [100] (::Observables.var"#callback#13"{Observables.var"#15#16"{Makie.var"#437#444", Observable{Vector{Float32}}}, Tuple{Observable{Matrix{Float32}}, Observable{Any}, Observable{Any}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
--- the last 6 lines are repeated 1 more time ---
 [107] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [108] invokelatest
     @ .\essentials.jl:714 [inlined]
 [109] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [110] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
 [111] (::Makie.var"#142#144"{Attributes, Observable{Tuple{StepRangeLen{Float32, Float64, Float64, Int64}, StepRangeLen{Float32, Float64, Float64, Int64}, Matrix{Float32}}}, DataType})(kwargs::Tuple{}, args::Tuple{SubArray{Float64, 2, Array{Float64, 3}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64}, true}})
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\interfaces.jl:333
 [112] (::Observables.var"#callback#13"{Makie.var"#142#144"{Attributes, Observable{Tuple{StepRangeLen{Float32, Float64, Float64, Int64}, StepRangeLen{Float32, Float64, Float64, Int64}, Matrix{Float32}}}, DataType}, Tuple{Observable{Tuple{}}, Observable{Tuple{SubArray{Float64, 2, Array{Float64, 3}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Int64}, true}}}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
 [113] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [114] invokelatest
     @ .\essentials.jl:714 [inlined]
 [115] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [116] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
 [117] #15
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:393 [inlined]
--- the last 6 lines are repeated 1 more time ---
 [124] (::Observables.var"#callback#13"{Observables.var"#15#16"{typeof(get_slice_data), Observable{SubArray{Float64, 2, Array{Float64, 3}, Tuple{Base.Slice{Base.OneTo{Int64}}, 
Base.Slice{Base.OneTo{Int64}}, Int64}, true}}}, Tuple{Observable{Any}}})(x::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:339
 [125] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [126] invokelatest
     @ .\essentials.jl:714 [inlined]
 [127] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [128] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
 [129] (::Makie.var"#1472#1488"{Slider, Observable{Any}})(i::Int64)
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\makielayout\blocks\slider.jl:63
 [130] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [131] invokelatest
     @ .\essentials.jl:714 [inlined]
 [132] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [133] setindex!(observable::Observable, val::Any)
     @ Observables C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86
 [134] (::Makie.var"#1477#1493"{Slider, Observable{Float64}, Observable{Bool}, Observable{Int64}, Observable{Vector{Point{2, Float32}}}, Observable{Any}})(event::MouseEvent)   
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\makielayout\blocks\slider.jl:110
 [135] (::Makie.var"#1059#1060"{Makie.var"#1477#1493"{Slider, Observable{Float64}, Observable{Bool}, Observable{Int64}, Observable{Vector{Point{2, Float32}}}, Observable{Any}}})(event::MouseEvent)
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\makielayout\mousestatemachine.jl:86
 [136] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [137] invokelatest
     @ .\essentials.jl:714 [inlined]
 [138] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [139] setindex!
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86 [inlined]
 [140] (::Makie.var"#1101#1103"{Scene, Makie.var"#is_mouse_over_relevant_area#1100"{Scene, Observable{GeometryBasics.HyperRectangle{2, Float32}}}, Base.RefValue{Float64}, Base.RefValue{Bool}, Base.RefValue{Bool}, Base.RefValue{Union{Nothing, Makie.Mouse.Button}}, Base.RefValue{Bool}, Base.RefValue{Point{2, Float32}}, Base.RefValue{Point{2, Float32}}, Base.RefValue{Makie.Mouse.Action}, Observable{MouseEvent}, Module})(mp::Tuple{Float64, Float64})
     @ Makie C:\Users\Will Laptop\.julia\packages\Makie\Ppzqh\src\makielayout\mousestatemachine.jl:169
 [141] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [142] invokelatest
     @ .\essentials.jl:714 [inlined]
 [143] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [144] setindex!
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:86 [inlined]
 [145] (::GLMakie.MousePositionUpdater)(#unused#::Nothing)
     @ GLMakie C:\Users\Will Laptop\.julia\packages\GLMakie\K6iJk\src\events.jl:6
 [146] #invokelatest#2
     @ .\essentials.jl:716 [inlined]
 [147] invokelatest
     @ .\essentials.jl:714 [inlined]
 [148] notify
     @ C:\Users\Will Laptop\.julia\packages\Observables\ynr7h\src\Observables.jl:143 [inlined]
 [149] pollevents(screen::GLMakie.Screen)
     @ GLMakie C:\Users\Will Laptop\.julia\packages\GLMakie\K6iJk\src\screen.jl:49
 [150] fps_renderloop(screen::GLMakie.Screen, framerate::Float64)
     @ GLMakie C:\Users\Will Laptop\.julia\packages\GLMakie\K6iJk\src\rendering.jl:20
 [151] renderloop(screen::GLMakie.Screen; framerate::Float64)
     @ GLMakie C:\Users\Will Laptop\.julia\packages\GLMakie\K6iJk\src\rendering.jl:46
 [152] renderloop(screen::GLMakie.Screen)
     @ GLMakie C:\Users\Will Laptop\.julia\packages\GLMakie\K6iJk\src\rendering.jl:39
```

### PR DESCRIPTION
**Pull request by SimonDanisch**
Should fix #2200

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
This still doesn't work, but for a different reason:

```julia
d = Observable([sin(x) * cos(y) for x in 1:10, y in 1:10])
x = Observable(1:10)
y = Observable(1:10)
f, ax, con = contourf(x, y, d)

##

x.val = 1:20
y.val = 1:20
d[] = randn(20, 20)
```

**Comment by SimonDanisch** [comment]
I donnt think we can fix that right now, without a different approach in the conversion pipeline...

**Comment by jkrumbiegel** [comment]
No? The exact same code does work if you use `image` instead of `contourf`. There's just something not updating correctly

**Comment by SimonDanisch** [comment]
That's because Image doesn't care if dimensions don't match:
```julia
image(1:4, 1:20, rand(5, 7))
```
The image is interpolated to whatever rect x/y span...

**Comment by jkrumbiegel** [comment]
And heatmap?

File: ReferenceTests/src/tests/updating.jl [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    end
+
+    foreach(5:-1:1) do i
+        t[] = i
+        Makie.step!(st)
+    end
+    st
+end
+
+@reference_test "updating contourf" begin
```
Comment (jkrumbiegel) [inline ReferenceTests/src/tests/updating.jl:24]: not a contourf though! :)

**Comment by Boxylmer** [comment]
You guys are awesome! Thanks for taking the time to look around at it!
