### PR TITLE
Fix/Improve marker attribute compatibility with float32converts

### LINKED ISSUE #4867: `markerspace=:data` breaks after zooming in
If I zoom in, after a certain point, the markers disappear abruptly.

Reproducer and recording below:

```
using GLMakie
fig = Figure()
ax2 = Axis(fig[1,1])
obs = Observable(Point2f.([(0,0),(10,10)]))
scatter!(ax2, obs, markersize=1, markerspace=:data, marker=:rect)
fig
```

https://github.com/user-attachments/assets/fdc17655-12bb-4ba0-b569-8ce54039bda0

- [x] what version of Makie are you running? (`]st -m Makie`)

```
Status `/tmp/Project.toml`
  [e9467ef8] GLMakie v0.11.3
  [ee78f7c6] Makie v0.22.2
```

- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)

yes

- [x] What platform + GPU are you on?

Arch Linux, March 2025, Intel iGPU

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

Fixes #4867 ... mostly...

With `markerspace == :data` marker attributes are given in pre-float32convert units and therefore should apply float32converts. This pr adds that for scatter, fast-pixel scatter and text.

When `markerspace = :data`, `transform_marker = true`, the model matrix contains rotation and float32convert is not an identity, then the model matrix needs to be applied on the CPU. Doing that for scatter would require rewriting the shader, as the model matrix gets applied after various other calculations.

TODO:
- [x] fix incorrect marker and text placement after float32convert triggers/recalculates
- [x] update WGLMakie
- [x] update CairoMakie
- [x] add refimage tests
- [x] fix broken text layout with `markerspace = :pixel, transform_marker = true` in GLMakie 
- [ ] fix first display time

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: WGLMakie/src/particles.jl [hunk 1]
```diff
@@ -165,6 +167,24 @@ function serialize_three(fta::NoDataTextureAtlas)
     return tex
 end
 
+function add_f32c_scale!(uniforms, scene, plot, f32c)
```
Comment (SimonDanisch) [inline WGLMakie/src/particles.jl:170]: this looks like the same function as in GLMakie? Can we share them, and also put the huge comment from GLMakie there?

**Review by SimonDanisch — APPROVED** [review]
