### PR TITLE
Rebased version of beta 0.20

### LINKED ISSUE #1236: Documentation on `Zoom!`
Hello, I am trying to use the `zoom!` function, see [here](http://makie.juliaplots.org/stable/makie_api.html#Makie.zoom!-Tuple{Any,%20Union{Tuple{Vararg{T,%20N}},%20StaticArrays.StaticVector{N,%20T}}%20where%20{N,%20T},%20Any,%20Bool}), but there is no usable doc and no examples.

More generally, the doc is extremely hard to use: there are many functions who use `Vec3f0`, but I found no reference for this. For instance, `zoom(scene, Vec3f0(0,0,0), 2)` outputs a 
> no method matching zoom!(::Scene, ::Vec{3, Float32}, ::Int64)

so that I have no clue on how to use these Vec3f0 objects. 

I also have no clues on what are those `5f0` [often found in examples](https://lazarusa.github.io/BeautifulMakie/surfWireLines/), and I could not find something in the doc on them.

### LINKED ISSUE #1600: Broken camera rotation with upvector Z = 0
Manual 3D camera rotation seems broken if I define upvector Z coordinate to be exactly 0:

``` julia
using GLMakie
using GeometryBasics

scene = Scene()
solid = FRect3D(Vec3f0(-20,-10,0), Vec3f0(40,20,1))
mesh!(scene, solid, color = :red)

cam = cam3d!(scene)
center!(scene)
cam.upvector[] = Vec3f0(1, 0, 0)     #broken camera rotation
#cam.upvector[] = Vec3f0(1, 0, 1e-10)  #OK

update_cam!(scene, cam)
scene
```
Once I try to rotate the camera, the image disappears and the `cam.eyeposition` and `cam.upvector` become Vectors of `NaN`.

### LINKED ISSUE #2721: Fixed-axis camera rotation Y and Z axes swapped
I noticed that holding down the y or z keys while dragging to rotate the 3D scene appears to rotate about the wrong world axis (about y when z is pressed and vice versa).

I think the culprit is this line: https://github.com/MakieOrg/Makie.jl/blob/master/src/camera/camera3d.jl#L487:

```
rotation *= qrotation(
                Vec3f(fix_x, fix_z, fix_y) .* Vec3f(sign(right[1]), viewdir[2], sign(up[3])),
                dot(Vec3f(fix_x, fix_y, fix_z), angles)
            )
```

Just swapping the 2nd and 3rd arguments to the first `Vec3f` appears to fix the issue.

### LINKED ISSUE #2985: Issue with typing on LScene with lights
The following fails:

```julia
julia> using RPRMakie
julia> let
           fig = Figure();
           radiance = 10000
           lights = [PointLight(Vec3f(0, 0, 20), RGBf(radiance, radiance, radiance))]
           ax = LScene(fig[1, 1]; show_axis = false, scenekw=(lights=lights,))
       end
ERROR: MethodError: no method matching Scene(::Scene, ::Events, ::Observable{GeometryBasics.HyperRectangle{2, Int64}}, ::Observable{Bool}, ::Camera, ::EmptyCamera, ::Transformation, ::Vector{AbstractPlot}, ::Attributes, ::Vector{Scene}, ::Vector{MakieScreen}, ::Observable{ColorTypes.RGBA{Float32}}, ::Observable{Bool}, ::SSAO, ::Vector{PointLight})

Closest candidates are:
  Scene(::Union{Nothing, Scene}, ::Events, ::Observable{GeometryBasics.HyperRectangle{2, Int64}}, ::Observable{Bool}, ::Camera, ::AbstractCamera, ::Transformation, ::Vector{AbstractPlot}, ::Attributes, ::Vector{Scene}, ::Vector{MakieScreen}, ::Observable{ColorTypes.RGBA{Float32}}, ::Observable{Bool}, ::SSAO, ::Vector{Makie.AbstractLight})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\scenes.jl:118
  Scene(::Scene, ::Any; kw...)
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\scenes.jl:345
  Scene(::Scene; events, px_area, clear, camera, camera_controls, transformation, kw...)
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\scenes.jl:303

Stacktrace:
 [1] Scene(; px_area::Observable{GeometryBasics.HyperRectangle{2, Int64}}, events::Events, clear::Observable{Bool}, transform_func::Function, camera::typeof(cam3d!), camera_controls::EmptyCamera, transformation::Transformation, plots::Vector{AbstractPlot}, children::Vector{Scene}, current_screens::Vector{MakieScreen}, parent::Scene, visible::Observable{Bool}, ssao::SSAO, lights::Vector{PointLight}, theme::Attributes, theme_kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\scenes.jl:253
 [2] Scene(parent::Scene; events::Events, px_area::Observable{GeometryBasics.HyperRectangle{2, Int64}}, clear::Bool, camera::Function, camera_controls::Makie.PixelCamera, transformation::Transformation, kw::Base.Pairs{Symbol, Vector{PointLight}, Tuple{Symbol}, NamedTuple{(:lights,), Tuple{Vector{PointLight}}}})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\scenes.jl:318
 [3] Scene(parent::Scene, area::Observable{GeometryBasics.HyperRectangle{2, Int64}}; kw::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:clear, :camera, :lights), Tuple{Bool, typeof(cam3d!), Vector{PointLight}}}})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\scenes.jl:346
 [4] initialize_block!(ls::LScene; scenekw::NamedTuple{(:lights,), Tuple{Vector{PointLight}}})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\makielayout\blocks\scene.jl:23
 [5] _block(::Type{LScene}, ::Figure; bbox::Nothing, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:show_axis, :scenekw), Tuple{Bool, NamedTuple{(:lights,), Tuple{Vector{PointLight}}}}}})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\makielayout\blocks.jl:374
 [6] _block(::Type{LScene}, ::GridPosition; kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:show_axis, :scenekw), Tuple{Bool, NamedTuple{(:lights,), Tuple{Vector{PointLight}}}}}})
   @ Makie C:\Users\User\.julia\packages\Makie\DekzU\src\makielayout\blocks.jl:268
 [7] _block
   @ C:\Users\User\.julia\packages\Makie\DekzU\src\makielayout\blocks.jl:261 [inlined]
 [8] #_#1103
   @ C:\Users\User\.julia\packages\Makie\DekzU\src\makielayout\blocks.jl:253 [inlined]
 [9] top-level scope
   @ REPL[13]:5
```

since `typeof(lights) == Vector{PointLight}`. If instead `typeof(lights) == Vector{AbstractLight}`, it works:

```julia
julia> let
           fig = Figure();
           radiance = 10000
           lights = Vector{Makie.AbstractLight}([PointLight(Vec3f(0, 0, 20), RGBf(radiance, radiance, radiance))])
           ax = LScene(fig[1, 1]; show_axis = false, scenekw=(lights=lights,))
       end
LScene()
```

Code's taken from https://docs.makie.org/stable/documentation/backends/rprmakie/, on:

```julia
julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 32 × 13th Gen Intel(R) Core(TM) i9-13900K
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, goldmont)
  Threads: 1 on 32 virtual cores

(jl_8jzM0Y) pkg> st
Status `C:\Users\User\AppData\Local\Temp\jl_8jzM0Y\Project.toml`
  [22d9f318] RPRMakie v0.5.5
```

### LINKED ISSUE #3238: Point light color is ignored in GLMakie
```julia
using GLMakie
using FileIO

GLMakie.closeall()

brain = load(assetpath("brain.stl"))

f = Figure()

ls = LScene(f[1, 1]; scenekw = (; lights = Makie.AbstractLight[PointLight(Point3f(100, 100, 100), RGBf(1, 0, 0))]))

mesh!(ls, brain, color = :white)

f
```

Gives this:

grafik

No hint of red to be seen. I've followed the tracks a bit and think the problem is that in `mesh.frag` we have

```glsl
void main(){
    vec4 color;
    // Should this be a mustache replace?
    if (fetch_pixel){
        color = get_pattern_color(image);
    }else{
        color = get_color(image, o_uv, color_norm, color_map, matcap);
    }
    {{light_calc}}
    write2framebuffer(color, o_id);
}
```

and in `surface.jl` we have

```julia
function light_calc(x::Bool)
    if x
        """
        vec3 L      = normalize(o_lightdir);
        vec3 N      = normalize(o_normal);
        vec3 light1 = blinnphong(N, o_camdir, L, color.rgb);
        vec3 light2 = blinnphong(N, o_camdir, -L, color.rgb);
        color       = vec4(ambient * color.rgb + light1 + backlight * light2, color.a);
        """
    else
        ""
    end
end
```

And then we have 

```glsl
vec3 blinnphong(vec3 N, vec3 V, vec3 L, vec3 color){
    float diff_coeff = max(dot(L, N), 0.0);

    // specular coefficient
    vec3 H = normalize(L + V);

    float spec_coeff = pow(max(dot(H, N), 0.0), shininess);
    if (diff_coeff <= 0.0 || isnan(spec_coeff))
        spec_coeff = 0.0;

    // final lighting model
    return vec3(
        diffuse * diff_coeff * color +
        specular * spec_coeff
    );
}
```

So `color` in `blinnphong` which to me should be the light color seems to be the texture color instead unless I'm misunderstanding.

### LINKED ISSUE #3239: Directional light as new default
Right now we don't have the light type directional light at all in GLMakie and WGLMakie. This is a light like the sun, like a point light at infinite distance so that all rays are parallel. This is nice because it's easy to light any object without worrying about anything but the light angle.

Therefore, I think we should add this light type to Makie and actually make it the default. Right now, the default is a point light that is placed at eye position. This is not great I think, because lighting from eye position means there aren't any visible shadow areas, which reduces the three-dimensionality of the lit surfaces. I understand that this choice was made because it was the only simple choice available. For any other position of a point light, one would probably need to take object positions and sizes into account. Not so with a directional light. A good default could be a light coming from top right of eye position.

I already tried tinkering with this a little bit and hit https://github.com/MakieOrg/Makie.jl/issues/3238 in the process. The glmakie light pipeline appeared much more hardcoded to one point and one ambient light to me than I had assumed prior given the `lights` Vector being able to hold an arbitrary number of arbitrary light types. So this might need a larger refactor. Or we add direction-ness as a boolean Switch to PointLight which would change how the Point3f it holds is interpreted, as a position or a direction.

### LINKED ISSUE #3307: Poor performance of scatter with non-scalar markersize
This is a performance issue. When calling `scatter` with a `markersize` that is a collection (say, a `Vector`) the performance of `display` is around ~200 times slower than with a scalar `markersize`. `meshscatter` does not have this problem, so I suspect it is a missed optimization of some kind.

Reproducer (timings and allocs are second-run)
```julia
julia> r = 10 * rand(Point3, 200000); s = rand(200000);

julia> @time display(scatter(r, markersize = 0.5));
  0.106780 seconds (58.04 k allocations: 8.244 MiB, 6.92% compilation time)

julia> @time display(scatter(r, markersize = s));
 18.634452 seconds (333.85 M allocations: 16.129 GiB, 3.90% gc time, 0.02% compilation time)

julia> @time display(meshscatter(r, markersize = s));
  0.024103 seconds (49.81 k allocations: 10.078 MiB)
```

- [x] are you running newest version (version from docs) ? Yes
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) Yes
- [x] What platform + GPU are you on? Macbook Pro M1, macos Sonoma 14.0

### PR DESCRIPTION
**Pull request by SimonDanisch**
Continues #2831 !
Still needs to check, if I rebased correctly and didn't incorrectly apply some of the changes!

## Merged PRs
- https://github.com/MakieOrg/Makie.jl/pull/2598
- https://github.com/MakieOrg/Makie.jl/pull/2746
- https://github.com/MakieOrg/Makie.jl/pull/2346
- https://github.com/MakieOrg/Makie.jl/pull/2544
- https://github.com/MakieOrg/Makie.jl/pull/3082
- #2868
- #3062
- #3106
- #3281
- #3246

## TODOS

- [x] fix flaky test `@test GLMakie.window_size(screen.glscreen) == scaled(screen, (W, H))`
- [x] Merge axis type inferences from #2220 
- [x] Test on different resolution screens, IJulia, Pluto, VSCode, Windowed
- [x] rebase to only have merge commits from the PRs 
- [x] investigate unexpected speed ups
- [x] reset camera settings from tests
- [ ] check doc image generation
- [x] rethink default near/far in Camera3D (compatability with OIT)
- [x] merge #3246
- [x] fix WGLMakie issues/tests:
  - [x] fix line depth issues (see tests: ~~hexbin colorrange~~ (not new), LaTeXStrings in Axis3, Axis3 axis reversal)
  - [x] fix lighting of surface with nan points (fixed in #3246)
  - ~~volume/3D contour artifacts (see 3D Contour with 2D contour slices)~~ not new
  - ~~artifacting in "colorscale (lines)"~~ not new
- [x] GLMakie:
  - [x] slight outline in "scatter image markers" test
  - ~~clipping/z-fighting in "volume translated"~~ not new
- [x] CairoMakie:
  -  ~~Artfiacting in `colorscale (lines)"~~ not new
  - ~~markersize in "scatter rotations" changed?~~ not new
  - ~~color change in "colorscale (poly)"~~ not new
  - ~~transparency/render order of "OldAxis + Surface"~~ not new
  - ~~render order in "Merged color mesh"~~ not new
  - ~~render order of "Surface + wireframe + contour"~~ not new
- [x] Check "SpecApi in convert_arguments" (colors swapped?)

## Fixes the following errors

- fixes #2721 via #2746
- fixes #1600 via #2746
- fixes #1236 via #2746
- fixes https://github.com/MakieOrg/GeoMakie.jl/issues/133 via #2598
- closes https://github.com/MakieOrg/Makie.jl/issues/2522
- closes #3239 via #3246
- fixes #3238 via #3246
- fixes #2985 via #3246
- fixes #3307 via #3281

### CODE REVIEW

File: CairoMakie/src/screen.jl [hunk 1]
```diff
@@ -81,8 +81,8 @@ end
 to_cairo_antialias(aa::Int) = aa
 
 """
-* `px_per_unit = 2.0`: see [figure docs](https://docs.makie.org/stable/documentation/figure/).
-* `pt_per_unit = 0.75`: see [figure docs](https://docs.makie.org/stable/documentation/figure/).
+* `px_per_unit = 2.0`: see [figure docs](https://docs.makie.org/stable/documentation/figure_size/).
```
Comment (SimonDanisch) [inline CairoMakie/src/screen.jl:84]: @jkrumbiegel I guess this is the old url and should be figure now? Or is this the correct fix?

Comment (jkrumbiegel) [reply CairoMakie/src/screen.jl:84]: hm that page does exist and in principle contains the right info. But I feel like I have rewritten that section at some point to explain the new changes. Or haven't I? It was too long ago..

Comment (jkrumbiegel) [reply CairoMakie/src/screen.jl:84]: ah the github interface for some reason didn't show the right changes, ok yeah I see now that I deleted that page in the refactor. So yeah link needs to be fixed

**Comment by ffreyer** [comment]
I would like to get #3106 in here too so we don't have two releases messing with the visuals of surface.

**Comment by SimonDanisch** [comment]
Yes, definitely! We also should merge https://github.com/MakieOrg/Makie.jl/pull/2756 as part of that!

File: GLMakie/test/unit_tests.jl [hunk 2]
```diff
@@ -255,3 +257,132 @@ end
...
+        # save at current size
+        @test screen.px_per_unit[] == 1
+        save(file, fig)
+        img = load(file)
+        @test size(img) == (W, H)
+
+        # save with a different resolution
+        save(file, fig, px_per_unit = 2)
+        img = load(file)
+        @test size(img) == (2W, 2H)
```
Comment (ffreyer) [inline GLMakie/test/unit_tests.jl:326]: This fails for me locally now.
```julia
  Expression: size(img) == (2W, 2H)
   Evaluated: (400, 400) == (800, 800)
```

File: GLMakie/src/drawing_primitives.jl [hunk 3]
```diff
@@ -280,8 +281,15 @@ function draw_atomic(screen::Screen, scene::Scene, @nospecialize(x::Lines))
         data = Dict{Symbol, Any}(gl_attributes)
 
         positions = handle_view(x[1], data)
+
         transform_func = transform_func_obs(x)
 
+        # Tweak things for px_per_unit
+        resolution = pop!(data, :resolution)
+        px_per_unit = data[:px_per_unit]
+        data[:resolution] = map((ppu, res) -> ppu .* res, px_per_unit, resolution)
```
Comment (ffreyer) [inline GLMakie/src/drawing_primitives.jl:290]: Should we move this to `connect_camera!`? This effectively makes the `resolution` in shaders the true pixel resolution rather than the (potentially) scaled user resolution. Would require one or two tweaks in the scatter shader, not really simplifying or complicating anything...

Comment (SimonDanisch) [reply GLMakie/src/drawing_primitives.jl:290]: Yeah sounds good! Would also be nice to document this a bit more... I'm pretty lost, where we use which unit/resolution at this point :D I also have the suspicion, that WGLMakie does it a bit different, but comes to the same result..

Comment (ffreyer) [reply GLMakie/src/drawing_primitives.jl:290]: Ok, how should I change this here? I assume we want to avoid small commits, so should I make a pr to this branch? Or just push one commit directly and hope nothing else needs changing as a result?

Comment (SimonDanisch) [reply GLMakie/src/drawing_primitives.jl:290]: I think a PR against this branch that we squash merge would be best!

**Comment by ffreyer** [comment]
I just noticed that you can run into `ERROR: znear (0.0) must be different from tfar (0.0)` with something like a `meshscatter` with the same repeated positional argument. We should check for that in update_cam! and avoid the error

**Comment by ffreyer** [comment]
I updated the first post with a bunch of issues I saw in refimgs. They might not all be relevant to this pr and some may change again with the lighting pr merged

**Comment by lazarusA** [comment]
the following use to work without the `center!(axs.scene)`, now is necessary. This works if is displayed first.

```Julia
using GLMakie, LaTeXStrings, Colors, ColorSchemes
using FileIO
GLMakie.activate!()

function alpha_colorbuffer(scene)
    bg = scene.backgroundcolor[]
    scene.backgroundcolor[] = RGBAf(0, 0, 0, 1)
    b1 = copy(Makie.colorbuffer(scene))
    scene.backgroundcolor[] = RGBAf(1, 1, 1, 1)
    b2 = Makie.colorbuffer(scene)
    scene.backgroundcolor[] = bg
    return map(infer_alphacolor, b1, b2)
end

function infer_alphacolor(rgb1, rgb2)
    rgb1 == rgb2 && return RGBAf(rgb1.r, rgb1.g, rgb1.b, 1)
    c1 = Float64.((rgb1.r, rgb1.g, rgb1.b))
    c2 = Float64.((rgb2.r, rgb2.g, rgb2.b))
    alpha = @. 1 - (c1 - c2) * -1 # ( / (0 - 1))
    meanalpha = clamp(sum(alpha) / 3, 0, 1)
    meanalpha == 0 && return RGBAf(0, 0, 0, 0)
    c = @. clamp((c1 / meanalpha), 0, 1)
    return RGBAf(c..., meanalpha)
end

xx = 10 .^ (range(-1.5, stop = log10(4), length = 20))
xx = vcat([0], xx)
x = y = vcat(-xx[end:-1:1], xx)
x3 = -4:0.25:4
y3 = -4:0.25:4
r(i, j) = sqrt(i^2 + j^2)

z3 = [-1.5 / (1 + r(i, j))^(1 / 2) for i in x3, j in y3]
x2 = -10:0.25:10
y2 = -10:0.25:10
z2 = [0 for i in x2, j in y2]

pot(i, j) = -1.5 / (1 + r(i, j))^(1 / 2)
xx = 10 .^ (range(-1.5, stop = log10(4), length = 50))
xx = vcat([0], xx)
θ = collect(range(0, 2π, length = 50))

x2 = xx .* cos.(θ)'
y2 = xx .* sin.(θ)'
z2 = pot.(x2, y2)
vol = [-1.5 / (1 + r(i, j))^(1 / 2) for i in x, j in y]

n = 101
cmap = :cyclic_tritanopic_wrwc_70_100_c20_n256
g(x) = exp(-x^2)
alphas = [g(x) for x in range(-2, 3, 101)]
cmap = resample_cmap(cmap, n; alpha=alphas)
s = 8.0

fig = with_theme(theme_dark()) do
    fig = Figure(resolution = (1200, 1200))
    axs = LScene(fig[1, 1], show_axis = false)
    surface!(axs, x2, y2, z2, colormap = cmap, #colorrange = (0, 1.5),
        transparency = :true)
    surface!(axs, x2 .+ s, y2, z2, colormap = cmap, #colorrange = (0, 1.5),
        transparency = :true)
    surface!(axs, x2 .+ s, y2 .+ s, z2, colormap = cmap, #colorrange = (0, 1.5),
        transparency = :true)
    surface!(axs, x2, y2 .+ s, z2, colormap = cmap, #colorrange = (0, 1.5),
        transparency = :true)
    wireframe!(axs, x2, y2, z2, color = (:grey65, 0.1), transparency = true)
    wireframe!(axs, x2 .+ s, y2, z2, color = (:grey65, 0.15), transparency = true)
    wireframe!(axs, x2 .+ s, y2 .+ s, z2, color = (:grey65, 0.35), transparency = true)
    wireframe!(axs, x2, y2 .+ s, z2, color = (:grey65, 0.15), transparency = true)

    meshscatter!(axs, Point3f(0, 0, 0.2); color = "#e4c92a", markersize = 1.2)
    meshscatter!(axs, Point3f(0 + s, 0, 0.2); color = :white, markersize = 1.0)
    meshscatter!(axs, Point3f(0 + s, 0 + s, 0.2); color = "#dd3365", markersize = 1.0)
    meshscatter!(axs, Point3f(0, 0 + s, 0.2); color = "#3782b9", markersize = 1.0)
    zoom!(axs.scene, cameracontrols(axs.scene), 0.87)
    center!(axs.scene)
    fig
end
save("test_alpha_s_new_new.png", alpha_colorbuffer(fig.scene))
```

**Comment by SimonDanisch** [comment]
Some more TODOs:

- [ ] Deprecate ContinuosSurface properly (again)
- [ ] Picking pixel mapping in WGLMakie
- [ ] For the above, `center!` shouldn't be needed. I think it's due to moving center to `reset_limits(::LScene)`

**Comment by SimonDanisch** [comment]
BeautifulMakie SSAO example seems broken:
```julia
using GLMakie, Colors, LinearAlgebra
using GeometryBasics, Downloads, FileIO
GLMakie.activate!(ssao=true)
GLMakie.closeall() # close any open screen
link = "https://www.solarsystemscope.com/textures/download/8k_earth_daymap.jpg"
earth_img = load(Downloads.download(link))
function SphereTess(; o=Point3f(0), r=1, tess=64)
    return uv_normal_mesh(Tesselation(Sphere(o, r), tess))
end
function ssaoplanes()
    fig = Figure()
    ssao = Makie.SSAO(radius = 5.0, blur = 3)
    ax = LScene(fig[1, 1]; show_axis=false, scenekw=(ssao=ssao,))
    ax.scene.ssao.bias[] = 0.025
    mesh!(ax, SphereTess(; o=Point3f(0.1, 0, 0), r=0.95);
        color=circshift(earth_img, (0, 3000)), ssao=true)
    # box
    mesh!(ax, Rect3(Vec3f(-1, -1, -1.1), Vec3f(2, 2, 0.1));
        color=RGB(0.082, 0.643, 0.918), ssao=true)
    mesh!(ax, Rect3(Vec3f(-1, -1.1, -1.1), Vec3f(2, 0.1, 2.1));
        color=RGB(0.929, 0.773, 0.0), ssao=true)
    mesh!(ax, Rect3(Vec3f(-1, -1, -1.0), Vec3f(0.1, 2, 2.0));
        color=RGB(0.91, 0.122, 0.361),
        ssao=true)
    fig
end
fig = with_theme(ssaoplanes, theme_dark())
```
image

**Comment by SimonDanisch** [comment]
```julia
using GLMakie, ColorSchemes
using GeometryBasics: Rect3f
GLMakie.activate!() # hide

x = y = z = -1:0.2:1
vol1 = [ix * iy * iz for ix in x, iy in y, iz in z]
points3d = [Point3f(ix, iy, iz) for ix in x, iy in y, iz in z];
## scale everything to the interval 0,1 (things don't seem to work with colorrange)
vol2 = (vol1 .+ 1) ./ 2;
## colormap with transparency in the middle
cmap = :Hiroshige
n = 101
g(x) = x^2
alphas = [g(x) for x in range(-1, 1, length = n)]
cmap_alpha = resample_cmap(cmap, n; alpha = alphas)
## the plot
fig = Figure(resolution = (1200, 1200))
ax2 = Axis3(fig[1, 1], perspectiveness = 0.5, azimuth = 6.62,
    elevation = 0.57, aspect = (1, 1, 1))

# volume!(ax1, x, y, z, vol2; colormap = cmap, transparency = true)
contour!(ax2, x, y, z, vol1; colormap = cmap, alpha = 0.05,
    levels = [collect(-1:0.01:-0.3)..., collect(0.3:0.01:1)...])

fig
```
Now has weird black cubes in the corners:
image

**Comment by SimonDanisch** [comment]
Text gets transformed in Axis3 now:
```julia
begin
    fig = Figure()
    ax = Axis3(fig[1, 1];
        aspect=(1, 0.5, 0.5),
        azimuth=10.42,
        elevation=0.027,
        perspectiveness=0.5)
    meshscatter!(ax, rand(Point3f, 10))
    text!(ax, Point3f(0), color=:black, fontsize=10, text="hiii")
    fig
end
```
(left tagged, right this PR)
image

**Comment by ffreyer** [comment]
> Text gets transformed in Axis3 now:
> 
> ```julia
> begin
>     fig = Figure()
>     ax = Axis3(fig[1, 1];
>         aspect=(1, 0.5, 0.5),
>         azimuth=10.42,
>         elevation=0.027,
>         perspectiveness=0.5)
>     meshscatter!(ax, rand(Point3f, 10))
>     text!(ax, Point3f(0), color=:black, fontsize=10, text="hiii")
>     fig
> end
> ```
> 
> (left tagged, right this PR) image
> 
> This leads to e.g. https://beautiful.makie.org/dev/examples/generated/2d/surfaces/band3d/?h=band to have a fontsize of ~400

Because scalings moved to `model/transformations` and text defaults to `transform_marker = true`

**Comment by ffreyer** [comment]
Fixed WGLMakie surface rendering which was still doing the centered color sampling from https://github.com/MakieOrg/Makie.jl/pull/2598#discussion_r1152552196

TODO - There is still a problem with z data -> color conversion: (GLMakie | WGLMakie)
Screenshot from 2023-11-03 12-09-05

I activated a bunch of refimg tests that should probably pass, including this one which shouldn't. 

> Makes sense... Does any disadvantage come to mind, when setting `transform_marker=false` for text as a default? I think usually that's what you want right? I'm just a bit afraid, that something depends on that behaviour somehow :D

It should only affect whether `model` applies to the generated quad or not. I.e. it translates/rotates/scales glyphs. That might be what you want with `markerspace = :data` otherwise I don't think so.

**Comment by ffreyer** [comment]
> Some more TODOs:
>
> * [x]  deprecate `shading=false` gracefully (set it to NoShading and not automatic)

Fixed

**Comment by ffreyer** [comment]
> ```julia
> using GLMakie
> cmap = :Hiroshige
> n = 101
> x = y = z = -1:0.2:1
> vol1 = [ix * iy * iz for ix in x, iy in y, iz in z]
> fig = Figure(resolution=(1200, 1200))
> ax2 = Axis3(fig[1, 1], perspectiveness=0.5, azimuth=6.62,
>     elevation=0.57, aspect=(1, 1, 1))
> contour!(ax2, x, y, z, vol1; colormap=cmap, alpha=0.05,
>     levels=[collect(-1:0.01:-0.3)..., collect(0.3:0.01:1)...])
> 
> fig
> ```
> 
> Now has weird black cubes in the corners: image

Fixed.

This was coming from `gennormal`. Near the edge the texture sampling returns the same position because there is no interpolation between a pixel/voxel center and the edge of the texture. I fixed this by sampling positions one edge-to-center distance apart:

Screenshot from 2023-11-03 15-21-00

I also fixed `shading = NoShading` not working with volume plots.

File: GLMakie/assets/shader/volume.frag [hunk 4]
```diff
@@ -96,32 +105,33 @@ vec3 gennormal(vec3 uvw, float d)
...
-    a.z = texture(volumedata, uvw - vec3(0.0,0.0,d)).r;
-    b.z = texture(volumedata, uvw + vec3(0.0,0.0,d)).r;
-    return normalize(a-b);
+    a.z = texture(volumedata, uvw - vec3(0.0, 0.0, o.z)).r;
+    b.z = texture(volumedata, uvw + vec3(0.0, 0.0, o.z)).r;
+
+    vec3 diff = a - b;
+    float n = length(diff);
+
+    if (n < 0.000000000001) // 1e-12
```
Comment (Moelf) [inline GLMakie/assets/shader/volume.frag:120]:
```suggestion
    if (n < 1e-12)
```

Comment (SimonDanisch) [reply GLMakie/assets/shader/volume.frag:120]: I don't think GLSL supports that syntax?

Comment (Moelf) [reply GLMakie/assets/shader/volume.frag:120]: you're right https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)
