### PR TITLE
Use `Base.depwarn()` exclusively, and fix deprecation tests

### LINKED ISSUE #4308: Precompilation warnings
- [x ] what version of Makie are you running? (`]st -m Makie`)
GLMakie v0.10.9

- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
Ubuntu 24.04 on AMD Ryzen 7840u

```
┌ GLMakie
│  WARNING: Makie.ContinuousSurface is deprecated, use VertexGrid instead.
│    likely near none:1
│  WARNING: importing deprecated binding Makie.ContinuousSurface into GLMakie.
│  , use VertexGrid instead.
│  WARNING: Makie.DiscreteSurface is deprecated, use CellGrid instead.
│    likely near none:1
│  WARNING: importing deprecated binding Makie.DiscreteSurface into GLMakie.
│  , use CellGrid instead.
│  
│  [pid 54682] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0x62d22e0->0x75755b1a12a0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└  
```

### PR DESCRIPTION
**Pull request by JamesWrigley**
# Description

Partially fixes #4308.

A few changes:
- Use `Base.depwarn()` instead of `Base.@deprecate_binding` to avoid warnings when importing symbols.
- Pass the missing `funcsym` argument to `Base.depwarn()` in `Combined()`.
- Fix the deprecation tests. Most of them were actually getting skipped because `@depwarn_message` had a `return` statement, causing the entire testset to return early as soon as the passed expression was evaluated.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

(I don't think this needs a changelog entry?)

- [ ] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: src/deprecated.jl [hunk 1]
```diff
@@ -1,8 +1,16 @@
 ###########################################
 # v0.20 deprecations:
 ##
-Base.@deprecate_binding DiscreteSurface CellGrid true
-Base.@deprecate_binding ContinuousSurface VertexGrid true
+
+function DiscreteSurface(args...; kwargs...)
+    Base.depwarn("Makie.DiscreteSurface() is deprecated, use Makie.CellGrid() instead", :DiscreteSurface)
```
Comment (SimonDanisch) [inline src/deprecated.jl:6]: Should we actually make this a warning with `maxlog=1`?
Every time we remove deprecations in a breaking version, people are confused why suddenly things are broken without a warning, since depwarns are turned off almost everywhere it matters for a plotting package.

Comment (jkrumbiegel) [reply src/deprecated.jl:6]: yeah I think that's better

Comment (JamesWrigley) [reply src/deprecated.jl]: Ok, changed to `@warn` in 5c3829cc2.

**Comment by SimonDanisch** [comment]
Thanks :)
