### PR TITLE
Fix errorbar and bracket interaction with transform functions

### LINKED ISSUE #3005: Whisker width on error bars does not work as expected on log scale plot.
I would like to display error bars on my graph which has the x axis plotted on a log scale. Choosing a large enough whisker width does allow them to show up, however, all whisker widths are of different sizes for each point, shown in below MWE (generated using CairoMakie):
```julia
f = Figure()
ax = Axis(f[1,1], xlabel="n", xscale=log10)
ns = 2 .^ 1:8
ys = sin.(ns)
errors = abs.(ys) ./ 10

errorbars!(ax, ns, ys, errors; whiskerwidth=100)
scatter!(ax, ns, ys)
display(f)
```
Result:
temp

How can one get constant width whiskers for the errorbars?

## Version Info

Makie: `[13f3f980] CairoMakie v0.10.6`
Julia: `v1.9.1`
OS: Windows 11

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

Fixes #3005 and #1455

I replaced `scene_to_screen` and `screen_to_scene` with `plot_to_screen` and `screen_to_plot` here, which includes applying the model matrix, transform function and considers `plot.space`. I changed the name because these functions are more closely related to what a plot is doing, and a plot can have different transformations (and coordinate space) than a scene.I'm also hoping it trips up CI if I missed some calls to the old functions.

This now also fixes some issues with bracket. On master it doesn't react to window resizing and it doesn't include transformations when calculating its positions.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: src/basic_recipes/bracket.jl [hunk 1]
```diff
@@ -105,10 +107,12 @@ function Makie.plot!(pl::Bracket)
...
     end
 
-    series!(pl, bp; space = :pixel, solid_color = pl.color, linewidth = pl.linewidth, linestyle = pl.linestyle)
+    # Avoid scale!() / translate!() / rotate!() to affect these
+    series!(pl, bp; space = :pixel, solid_color = pl.color, linewidth = pl.linewidth, 
+        linestyle = pl.linestyle, transformation = Transformation())
     text!(pl, textpoints, text = texts, space = :pixel, align = pl.align, offset = textoffset_vec,
         fontsize = pl.fontsize, font = pl.font, rotation = autorotations, color = pl.textcolor,
-        justification = pl.justification)
+        justification = pl.justification, model = Mat4f(I))
```
Comment (ffreyer) [inline src/basic_recipes/bracket.jl:115]: Currently `space = :pixel` still includes model transformation (at least in GLMakie). Since `plot_to_screen` deals with them now, they'd be included twice. To prevent that I'm overwriting model/transformation. I'm using transformation for series because model doesn't get passed down.

File: src/basic_recipes/error_and_rangebars.jl [hunk 2]
```diff
@@ -187,19 +187,18 @@ function _plot_bars!(plot, linesegpairs, is_in_y_direction)
 
     scene = parent_scene(plot)
 
-    whiskers = lift(plot, linesegpairs, scene.camera.projectionview,
-        scene.camera.pixel_space, whiskerwidth) do pairs, _, _, whiskerwidth
```
Comment (ffreyer) [inline src/basic_recipes/error_and_rangebars.jl:191]: With `camera.pixel_space` this sometimes fails to update correctly when zooming or resizing. `scene.px_area` works fine.

**Review by jkrumbiegel — APPROVED** [review]
