### PR TITLE
Fix transforming surface normals

### LINKED ISSUE #3702: Surface normals not properly transformed by `markersize` scaling.
To draw an ellipsoid, one can start with a sphere mesh and apply an anisotropic scaling via `markersize`:

```julia
using GLMakie
pts = Point3f[[0,0,0], [1,0,0]]
markersize = Vec3f[[0.5, 0.2, 0.5], [0.5, 0.2, 0.5]]
rotations = [qrotation(Vec3f(1,0,0), 0), qrotation(Vec3f(1,1,0), π/4)]
meshscatter(pts; markersize, rotations, color=:yellow)
```

image

The shading is wrong because the surface normals have not been properly transformed. @ffreyer pointed out on Slack that only one line of the GLMakie vertex shader should be changed: https://github.com/MakieOrg/Makie.jl/blob/14b65a0e8c786030f095cfe37860e6eaeec39eaa/GLMakie/assets/shader/particles.vert#L103

This line should read `vec3 N = normals / s;`. That is, it should include an element-wise _division_ by the scaling factors. With this fix, I get the correct visual result:

image

Presumably a similar change is needed for WGLMakie and CairoMakie, on these lines:
https://github.com/MakieOrg/Makie.jl/blob/14b65a0e8c786030f095cfe37860e6eaeec39eaa/WGLMakie/assets/particles.vert#L37
https://github.com/MakieOrg/Makie.jl/blob/14b65a0e8c786030f095cfe37860e6eaeec39eaa/CairoMakie/src/primitives.jl#L940

Below is a derivation explaining why its appropriate to divide by the scale factors.

image

### PR DESCRIPTION
**Pull request by singularitti**
# Description

Fixes #3702

As discussed in issue #3702, under the guidance of @kbarros, we made changes that solve the incorrect shading of ellipsoid surfaces of markers under light, displaying spherical reflections (mathematical formulae stated in #3702). The following figures show examples before and after this change. Please note that we are not experts in the GLSL language, so you may want to double-check whether this change may break some code. If you need changes to other backends, I am happy to help.

Testing code snippet:

```julia
using CairoMakie
# using GLMakie
# using WGLMakie
pts = Point3f[[0,0,0], [1,0,0]]
markersize = Vec3f[[0.5, 0.2, 0.5], [0.5, 0.2, 0.5]]
rotations = [qrotation(Vec3f(1,0,0), 0), qrotation(Vec3f(1,1,0), π/4)]
meshscatter(pts; markersize, rotations, color=:yellow)
```

### Before

cairomakie_before

### After

cairomakie_after

### Before

glmakie_before

### After

glmakie_after

### Before

wglmakie_before

### After

wglmakie_after

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: CairoMakie/src/primitives.jl [hunk 1]
```diff
@@ -932,7 +932,7 @@ function draw_mesh3D(
     projectionview = Makie.space_to_clip(scene.camera, space, true)
     eyeposition = scene.camera.eyeposition[]
     i = Vec(1, 2, 3)
-    normalmatrix = transpose(inv(model[i, i]))
+    normalmatrix = transpose(inv(model[i, i] * Diagonal(Vec3f(scale)))) # see issue #3702
```
Comment (ffreyer) [inline CairoMakie/src/primitives.jl:935]: This is also missing rotation, isn't it? I think we could just replace the diagonal matrix with the local_model matrix from below to fix that as well

**Comment by ffreyer** [comment]
Thanks for the pr.

Since none of the refimg tests are failing we should add a new one here. It would probably be good to use more extreme shading like `color=:white, diffuse = Vec3f(-2, 0, 4), specular = Vec3f(4, 0, -2)` to make the differences more obvious. Otherwise the test image comparison may struggle to pick up on it. The test would go in here: https://github.com/MakieOrg/Makie.jl/blob/master/ReferenceTests/src/tests/examples3d.jl

Other than that this just needs an entry in https://github.com/MakieOrg/Makie.jl/blob/master/CHANGELOG.md

**Comment by jkrumbiegel** [comment]
> Otherwise the test image comparison may struggle to pick up on it.

Thankfully the image comparison is a lot more sensitive nowadays, but it's still good practice to make failure modes as obvious as possible

File: CairoMakie/src/primitives.jl (hunk 1 above)
Comment (singularitti) [reply CairoMakie/src/primitives.jl]: Please see if it is fixed [here](https://github.com/MakieOrg/Makie.jl/pull/3722/commits/bdaddbdc11a3078333737e47dd74bc3f1eb4f0af).

**Comment by singularitti** [comment]
Done! Please have a look @ffreyer @jkrumbiegel:

## Before fixing rotations

cairomakie_before

## After fixing rotations

### CairoMakie

cairomakie_after

### GLMakie

glmakie_after

### WGLMakie

wglmakie_after

**Review by ffreyer — APPROVED** [review]
