### PR TITLE
Fix minorgridvisible not activating minortick updates

### LINKED ISSUE #4892: Minor grid lines are not displayed in a figure with boxplots, using Makie v0.22.0 to Makie v0.22.2
- [x ] what version of Makie are you running? (`]st -m Makie`)
Makie v0.22.0
- [x ] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
Yes

I create a figure with boxplots, which consists of 12 categories with 10 boxes in each category. I utilize the minor grid lines as separation between the categories. The minor grid lines are not displayed in the boxplot figure, when using recent Makie versions, even though xminorgridvisible = true. This happens starting with Makie v0.22.0. It still had been working well with Makie v0.21.18.

I replaced the actual data with randomly generated values in the script below, and I am able to reproduce the issue with that.

```julia
using CairoMakie

nmon = 1:12
nsim = 1:10
categories = rand( nmon, 1000 )
dodge = rand( nsim, 1000 )
zdata = rand( Float64, 1000 )

fig = Figure( size = (900, 500) )

Axis( fig[ 1, 1 ]; xlabel = "xlabel", ylabel = "ylabel", xgridvisible = false,
    xminorgridvisible = true, xminorgridstyle = :solid, xminorgridwidth = 1, xminorgridcolor = :black,
    xticksvisible = false, xticks = nmon, title = "plot title" )

boxplot!( fig[ 1, 1 ], categories, zdata, dodge = dodge, color = dodge )

xlims!( 0.5, 12.5 )

fig
```

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

Fixes #4892

Adds another bool to keep calculations active when needed from the outside

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Added an entry in CHANGELOG.md (for new features and breaking changes)
- [ ] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

File: src/makielayout/blocks/axis.jl [hunk 1]
```diff
@@ -327,6 +327,7 @@ function initialize_block!(ax::Axis; palette = nothing)
         ticklabelsize = ax.xticklabelsize, trimspine = ax.xtrimspine, ticksize = ax.xticksize,
         reversed = ax.xreversed, tickwidth = ax.xtickwidth, tickcolor = ax.xtickcolor,
         minorticksvisible = ax.xminorticksvisible, minortickalign = ax.xminortickalign, minorticksize = ax.xminorticksize, minortickwidth = ax.xminortickwidth, minortickcolor = ax.xminortickcolor, minorticks = ax.xminorticks, scale = ax.xscale,
+        minorticksused = ax.xminorgridvisible,
```
Comment (SimonDanisch) [inline src/makielayout/blocks/axis.jl:330]: What's the difference between `minorticksvisible = ax.xminorticksvisible` and `minorticksused = ax.xminorgridvisible` ?

**Comment by SimonDanisch** [comment]
I'm a bit confused.
Is the problem here, that `xminorgridvisible=true` doesn't show minorticks? 
It seems like `The minor grid lines are not displayed in the boxplot figure`. Are the gridlines connected to the ticks? I thought they'd be separate plots.

**Review by SimonDanisch — APPROVED** [review]
